#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 1000
#define SCREEN_HEIGHT 600
#define CURRENT_LEVEL 1

#define PLAYER_MAX_HEALTH 100
#define PLAYER_SWORD_DAMAGE 25
#define PLAYER_SPECIAL_DAMAGE 50

#define COMBO_REQUIRED_ATTACKS 3
#define COMBO_RESET_TIME 0.90f

#define PLAYER_IDLE_FRAMES 8
#define PLAYER_RUN_FRAMES 8
#define PLAYER_JUMP_FRAMES 6
#define PLAYER_ATTACK_FRAMES 8
#define PLAYER_HURT_FRAMES 3
#define PLAYER_DEATH_FRAMES 8
#define PLAYER_VICTORY_FRAMES 6

#define PLAYER_IDLE_SCALE 0.52f
#define PLAYER_RUN_SCALE 0.72f
#define PLAYER_JUMP_SCALE 0.52f
#define PLAYER_ATTACK_SCALE 0.78f
#define PLAYER_HURT_SCALE 0.52f
#define PLAYER_DEATH_SCALE 0.52f
#define PLAYER_VICTORY_SCALE 0.52f

#define PLAYER_ATTACK_GROUND_OFFSET 70.0f
#define PLAYER_HURT_GROUND_OFFSET 0.0f
#define PLAYER_DEATH_GROUND_OFFSET 0.0f
#define PLAYER_VICTORY_GROUND_OFFSET 0.0f

#define PLAYER_NORMAL_ATTACK_WIDTH 88.0f
#define PLAYER_SPECIAL_ATTACK_WIDTH 126.0f
#define PLAYER_NORMAL_ATTACK_HEIGHT 76.0f
#define PLAYER_SPECIAL_ATTACK_HEIGHT 94.0f
#define PLAYER_NORMAL_ATTACK_GAP 26.0f
#define PLAYER_SPECIAL_ATTACK_GAP 40.0f

#define PLAYER_HURT_FRAME_TIME 0.085f
#define PLAYER_DEATH_FRAME_TIME 0.110f
#define PLAYER_VICTORY_FRAME_TIME 0.140f
#define PLAYER_DEATH_HOLD_FRAME (PLAYER_DEATH_FRAMES - 1)
#define PLAYER_DEATH_FINAL_POSE_TIME 0.85f

#define PLAYER_GROUND_SPEED 220.0f
#define PLAYER_SPRINT_SPEED 340.0f
#define PLAYER_AIR_SPEED 440.0f
#define PLAYER_SPRINT_AIR_SPEED 535.0f
#define PLAYER_JUMP_FORCE -910.0f
#define PLAYER_GRAVITY 2000.0f

#define ZOMBIE_BASELINE_RATIO (226.0f / 256.0f)
#define ZOMBIE_PLAYER_HEIGHT_RATIO 0.68f
#define ZOMBIE_GROUND_OFFSET -48.0f

#define ZOMBIE_IDLE_FRAMES 8
#define ZOMBIE_WALK_FRAMES 8
#define ZOMBIE_ATTACK_FRAMES 8
#define ZOMBIE_HURT_FRAMES 4
#define ZOMBIE_DEATH_FRAMES 8
#define ZOMBIE_VICTORY_FRAMES 6

#define ZOMBIE_DEATH_HOLD_FRAME (ZOMBIE_DEATH_FRAMES - 1)
#define ZOMBIE_DEATH_FRAME_TIME 0.105f
#define ZOMBIE_DEATH_FINAL_POSE_TIME 0.85f

#define RESULT_PANEL_DELAY 3.00f

#endif
